import React from "react"
import { Link } from "gatsby"
import Layout from "../../components/layout"
import SEO from "../../components/seo"

const CONTACT_EMAIL = "me@maxlibin.com"
const APP_STORE_URL = "https://apps.apple.com/sg/app/homeworkai-psle-tutor/id6770512063"

const Section = ({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) => (
  <section className="mb-8">
    <h2 className="text-2xl font-bold text-fg mb-3">
      {title}
    </h2>
    <div className="text-muted space-y-3">{children}</div>
  </section>
)

const faqs = [
  {
    question: "How do I cancel my subscription?",
    answer:
      "Subscriptions are managed by Apple. On your device, open Settings → tap your name → Subscriptions → homeworkAI → Cancel Subscription. You'll keep Plus access until the end of the current billing period.",
  },
  {
    question: "I bought Plus on another device. How do I get it here?",
    answer:
      "Open the app, go to Me → Restore Purchases. Make sure you're signed in with the same Apple ID you used to buy Plus.",
  },
  {
    question: "The answer is wrong. Can I report it?",
    answer:
      "AI-generated answers can be wrong — that's why we treat the app as a study aid, not a teacher. If you spot a bad answer, email it to us and we'll use it to improve the prompts.",
  },
  {
    question: "How do I delete my child's history?",
    answer:
      "In History, swipe left on any entry to delete it. To wipe everything (history, grade, subject settings, parent PIN), go to Parent Zone → Reset everything. Deleting the app also removes all on-device data.",
  },
  {
    question: "How do I change the daily scan limit?",
    answer:
      "Free plan is capped at 3 scans a day. Plus is unlimited. The cap is enforced on-device and resets at local midnight.",
  },
  {
    question: "I forgot the Parent Zone PIN.",
    answer:
      "Open Settings → homeworkAI → and reset the app's data, then reinstall to start fresh. (We're working on a recovery flow.)",
  },
  {
    question: "Does the app work offline?",
    answer:
      "No — solving a question needs an internet connection because the answer is generated by a server-side AI model. Your history, however, is stored on-device and viewable offline.",
  },
  {
    question: "What languages are supported?",
    answer:
      "English and Simplified Chinese (简体中文). Switch in Me → Language.",
  },
]

const Support = () => {
  return (
    <Layout>
      <article className="mt-8 mb-16 px-4 md:px-0 max-w-3xl">
        <div className="mb-3 text-sm">
          <Link
            to="/homeworkai/"
            className="text-fg hover:underline"
          >
            ← homeworkAI
          </Link>
        </div>
        <h1 className="text-4xl font-extrabold text-fg mb-2">
          Support
        </h1>
        <p className="text-muted mb-10 max-w-2xl">
          The fastest way to get help is to email us. We read every message.
        </p>

        <Section title="Contact">
          <p>
            Email{" "}
            <a
              href={`mailto:${CONTACT_EMAIL}?subject=homeworkAI%20support`}
              className="text-fg hover:underline font-semibold"
            >
              {CONTACT_EMAIL}
            </a>{" "}
            with:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>What you were trying to do.</li>
            <li>What you saw instead.</li>
            <li>Your iPhone / iPad model and iOS version (if relevant).</li>
            <li>A screenshot or screen recording (if you have one).</li>
          </ul>
          <p>We aim to reply within 2 business days.</p>
        </Section>

        <Section title="FAQ">
          <div className="space-y-5">
            {faqs.map(f => (
              <div
                key={f.question}
                className="border-b border-line pb-4"
              >
                <h3 className="font-semibold text-fg mb-1">
                  {f.question}
                </h3>
                <p className="text-muted">{f.answer}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section title="Useful links">
          <ul className="list-disc pl-6 space-y-1">
            <li>
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="text-fg hover:underline"
              >
                homeworkAI on the App Store
              </a>
            </li>
            <li>
              <Link
                to="/homeworkai/privacy/"
                className="text-fg hover:underline"
              >
                Privacy Policy
              </Link>
            </li>
            <li>
              <Link
                to="/homeworkai/terms/"
                className="text-fg hover:underline"
              >
                Terms of Use
              </Link>
            </li>
          </ul>
        </Section>
      </article>
    </Layout>
  )
}

export default Support

export const Head = () => (
  <SEO
    title="homeworkAI — Support"
    description="Get help with homeworkAI. FAQ, subscription management, and how to reach us."
    pathname="/homeworkai/support/"
    breadcrumbs={[
      { name: "Home", item: "/" },
      { name: "homeworkAI", item: "/homeworkai/" },
      { name: "Support", item: "/homeworkai/support/" },
    ]}
    faqs={faqs}
  />
)
