import React from "react"
import { Link } from "gatsby"
import Layout from "../../components/layout"
import SEO from "../../components/seo"

const CONTACT_EMAIL = "me@maxlibin.com"
const EFFECTIVE_DATE = "20 May 2026"

const Section = ({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) => (
  <section className="mb-8">
    <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-3">
      {title}
    </h2>
    <div className="prose prose-gray dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 space-y-3">
      {children}
    </div>
  </section>
)

const Terms = () => {
  return (
    <Layout>
      <article className="mt-8 mb-16 px-4 md:px-0 max-w-3xl">
        <div className="mb-3 text-sm">
          <Link
            to="/homeworkai/"
            className="text-indigo-600 dark:text-indigo-400 hover:underline"
          >
            ← homeworkAI
          </Link>
        </div>
        <h1 className="text-4xl font-extrabold text-gray-900 dark:text-gray-100 mb-2">
          Terms of Use
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-10">
          Effective {EFFECTIVE_DATE}
        </p>

        <Section title="Agreement">
          <p>
            These Terms of Use ("Terms") are an agreement between you and Max
            Li Bin, an independent developer based in Singapore ("we", "us"),
            governing your use of the homeworkAI iOS app ("the app").
          </p>
          <p>
            By downloading, installing, or using the app you agree to these
            Terms and to our{" "}
            <Link
              to="/homeworkai/privacy/"
              className="text-indigo-600 dark:text-indigo-400 hover:underline"
            >
              Privacy Policy
            </Link>
            . If you don't agree, please don't use the app.
          </p>
        </Section>

        <Section title="Who can use the app">
          <p>
            The app is intended to be set up and supervised by a parent or
            guardian who is at least 18 years old. If you are under 18, you may
            only use the app with the involvement of a parent or guardian who
            agrees to these Terms on your behalf.
          </p>
        </Section>

        <Section title="What the app does">
          <p>
            homeworkAI lets you scan or type a homework question and returns a
            step-by-step explanation generated by AI. Answers are produced by
            large language models and are intended to support learning. They
            can be wrong, incomplete, or out of date. Always check important
            answers — the app is a study aid, not a substitute for a teacher.
          </p>
        </Section>

        <Section title="Subscriptions and billing">
          <p>
            homeworkAI is free to use with a daily scan limit. Plus is an
            auto-renewing subscription (monthly or yearly) sold and managed by
            Apple via the App Store.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Payment is charged to your Apple ID at confirmation of purchase.
            </li>
            <li>
              The subscription automatically renews for the same period unless
              auto-renew is turned off at least 24 hours before the end of the
              current period.
            </li>
            <li>
              The renewal charge is taken within 24 hours before the period
              ends.
            </li>
            <li>
              You can manage and cancel your subscription in Settings → Apple
              ID → Subscriptions on your device.
            </li>
            <li>
              Refunds (if any) are handled by Apple under the App Store's
              standard refund policy.
            </li>
          </ul>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Use the app for cheating in supervised exams or in any way that
              violates your school's academic rules.
            </li>
            <li>
              Upload content that is illegal, infringes someone else's rights,
              or contains personal information about another person without
              their permission.
            </li>
            <li>
              Attempt to reverse-engineer, scrape, or otherwise abuse the
              app or our backend, or to use it in a way that disrupts the
              service for other users.
            </li>
            <li>Use the app to develop a competing product.</li>
          </ul>
        </Section>

        <Section title="Your content">
          <p>
            You keep all rights to the homework photos and questions you submit.
            You grant us a limited, worldwide, royalty-free license to process
            that content for the sole purpose of operating the app — generating
            an answer, displaying your history, and improving reliability.
          </p>
        </Section>

        <Section title="Intellectual property">
          <p>
            The app, its design, branding, and code are owned by Max Li Bin and
            are protected by intellectual-property laws. We grant you a
            personal, non-exclusive, non-transferable, revocable license to use
            the app on Apple devices you own or control, in accordance with
            these Terms and Apple's standard EULA for App Store apps.
          </p>
        </Section>

        <Section title="Disclaimers">
          <p>
            The app is provided "as is" and "as available". To the maximum
            extent permitted by law, we disclaim all warranties, express or
            implied, including merchantability, fitness for a particular
            purpose, and non-infringement. AI-generated answers may be wrong;
            you are responsible for verifying them.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the maximum extent permitted by law, we will not be liable for
            any indirect, incidental, special, consequential, or punitive
            damages arising out of or relating to your use of the app. Our
            total liability for any claim arising out of or relating to these
            Terms is limited to the amount you paid us (via Apple) in the 12
            months before the claim arose, or, if you have not paid us
            anything, USD 50.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You can stop using the app at any time by deleting it. We may
            suspend or terminate your access to the app if you breach these
            Terms or if continuing the service becomes commercially or legally
            impractical.
          </p>
        </Section>

        <Section title="Changes to these Terms">
          <p>
            We may update these Terms from time to time. We'll change the
            effective date above and, for material changes, surface a notice in
            the app. Continuing to use the app after a change means you accept
            the updated Terms.
          </p>
        </Section>

        <Section title="Governing law">
          <p>
            These Terms are governed by the laws of Singapore, without regard
            to its conflict-of-laws rules. The courts of Singapore have
            exclusive jurisdiction over any dispute arising from these Terms,
            except where your local consumer-protection laws require otherwise.
          </p>
        </Section>

        <Section title="Apple-specific terms">
          <p>
            You acknowledge that these Terms are between you and us, not Apple,
            and that Apple is not responsible for the app or its content. To
            the extent these Terms are inconsistent with Apple's standard EULA
            for App Store apps, the terms more protective of you apply. Apple
            and its subsidiaries are third-party beneficiaries of these Terms
            and may enforce them against you.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these Terms?{" "}
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="text-indigo-600 dark:text-indigo-400 hover:underline"
            >
              {CONTACT_EMAIL}
            </a>
          </p>
        </Section>
      </article>
    </Layout>
  )
}

export default Terms

export const Head = () => (
  <SEO
    title="homeworkAI — Terms of Use"
    description="The agreement that governs your use of the homeworkAI iOS app: subscriptions, acceptable use, liability."
    pathname="/homeworkai/terms/"
    breadcrumbs={[
      { name: "Home", item: "/" },
      { name: "homeworkAI", item: "/homeworkai/" },
      { name: "Terms of Use", item: "/homeworkai/terms/" },
    ]}
  />
)
